batch_size: 4
checkpoint_dir: checkpoints/tracking
clip_length: 8
data_dir: D:\NCS\propose\dataset\MOT16
device: cuda
epochs: 10
eval_freq: 1
feature_channels: 128
latent_channels: 64
log_dir: logs
lr: 0.0001
num_workers: 4
rd_lambda: 0.01
resolution: 256
resume: ''
save_freq: 5
seed: 42
task_type: tracking
task_weight: 1.0
use_quantization: false
weight_decay: 1.0e-05
