batch_size: 1
checkpoint_dir: checkpoints
clip_length: 4
data_dir: D:/NCS/propose/dataset/MOT16
dataset_type: mot
device: cuda
epochs: 1
eval_freq: 1
feature_channels: 32
latent_channels: 16
log_dir: logs
lr: 0.0001
num_workers: 4
rd_lambda: 0.01
resolution: 256
resume: ''
save_freq: 5
seed: 42
task_type: detection
task_weight: 1.0
use_dummy_data: false
use_quantization: true
weight_decay: 1.0e-05
